version: '3'
services:
  app:
    image: "mcr.microsoft.com/devcontainers/dotnet:1-8.0-bookworm"
    volumes:
      - ../:/workspaces/cs-entity-framework
    working_dir: /workspaces/cs-entity-framework
    environment:
      - DB_HOST=db
      - DB_NAME=dev
      - DB_USER=dev
      - DB_PASSWORD=dev
    tty: true
    command: sleep infinity
  db:
    image: "mariadb:lts"
    environment:
      - MARIADB_ROOT_PASSWORD=dev
      - MARIADB_DATABASE=dev
      - MARIADB_USER=dev
      - MARIADB_PASSWORD=dev
